---
sudo: required
dist: xenial

language: python
python:
  - "2.7"
  - "3.5"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.9.7
  - ANSIBLE_VERSION=2.9.6
  - ANSIBLE_VERSION=2.9.5
  - ANSIBLE_VERSION=2.9.4
  - ANSIBLE_VERSION=2.9.3
  - ANSIBLE_VERSION=2.9.2
  - ANSIBLE_VERSION=2.9.1
  - ANSIBLE_VERSION=2.9.0
  - ANSIBLE_VERSION=2.8.11
  - ANSIBLE_VERSION=2.8.10
  - ANSIBLE_VERSION=2.8.9
  - ANSIBLE_VERSION=2.8.8
  - ANSIBLE_VERSION=2.8.7
  - ANSIBLE_VERSION=2.8.6
  - ANSIBLE_VERSION=2.8.5
  - ANSIBLE_VERSION=2.8.4
  - ANSIBLE_VERSION=2.8.3
  - ANSIBLE_VERSION=2.8.2
  - ANSIBLE_VERSION=2.8.1
  - ANSIBLE_VERSION=2.8.0
  - ANSIBLE_VERSION=2.7.17
  - ANSIBLE_VERSION=2.7.16
  - ANSIBLE_VERSION=2.7.15
  - ANSIBLE_VERSION=2.7.14
  - ANSIBLE_VERSION=2.7.13
  - ANSIBLE_VERSION=2.7.12
  - ANSIBLE_VERSION=2.7.11
  - ANSIBLE_VERSION=2.7.10
  - ANSIBLE_VERSION=2.7.9
  - ANSIBLE_VERSION=2.7.8
  - ANSIBLE_VERSION=2.7.7
  - ANSIBLE_VERSION=2.7.6
  - ANSIBLE_VERSION=2.7.5
  - ANSIBLE_VERSION=2.7.4
  - ANSIBLE_VERSION=2.7.3
  - ANSIBLE_VERSION=2.7.2
  - ANSIBLE_VERSION=2.7.1
  - ANSIBLE_VERSION=2.7.0
  - ANSIBLE_VERSION=2.6.20
  - ANSIBLE_VERSION=2.6.19
  - ANSIBLE_VERSION=2.6.18
  - ANSIBLE_VERSION=2.6.17
  - ANSIBLE_VERSION=2.6.16
  - ANSIBLE_VERSION=2.6.15
  - ANSIBLE_VERSION=2.6.14
  - ANSIBLE_VERSION=2.6.13
  - ANSIBLE_VERSION=2.6.12
  - ANSIBLE_VERSION=2.6.11
  - ANSIBLE_VERSION=2.6.10
  - ANSIBLE_VERSION=2.6.9
  - ANSIBLE_VERSION=2.6.8
  - ANSIBLE_VERSION=2.6.7
  - ANSIBLE_VERSION=2.6.6
  - ANSIBLE_VERSION=2.6.5
  - ANSIBLE_VERSION=2.6.4
  - ANSIBLE_VERSION=2.6.3
  - ANSIBLE_VERSION=2.6.2
  - ANSIBLE_VERSION=2.6.1
  - ANSIBLE_VERSION=2.6.0

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i tests/inventory tests/test.yml -vvvv

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - if [ "$ANSIBLE_VERSION" = "latest" ]; then ansible-lint tests/test.yml; fi

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      secure: "Aa3dRoUFjtzfOGpRnq4edhL2TBE8vPK3xhy9RDYoDU4yPe/KCQ5tqhs2AIER60/fnF01XCzIXc/88QuWQ2E3LDGMQzfgrJF+9Bw4n27zRjftKUTjMDyLvddhSksxH407HqEyYQIOCb2g1ixqwqiYGTtlqaBA8WlfNvGzUU3OqjrfahNyjkxjzGC9nfmCiFYV0w2iZAWleSSVUgHwzNXtqTNUEjpyzdiLmbIYiShgamTlXJA7iPGLp8yMxFeCRLIifiyUdp7wc9j4CznAhnhx3gYphXTaDj9GJCZ1DBTRZnUtAMEe27VWqtZub5gY//h4DbcazH9oSJzrdfsZ03iM4dT07irm6717fZlZzHdDydHPQh3SX5lU0h3cV/XR2dyF1W91XjMsIZ8p1FEFo7tS9nw73g/xaHjFfyASfqwWaO3lhEhJGe98zPZKBmcQmYRHD54UgkktppXtzJb1beqfF4VCK63D5FMWQ40L3FXW6lNgSvK29ar00fyi/p1zjr3UWKnvdn+xEkkncua6kiZi/2g+Pc9E52bYFmnxmSHKY1GjCGIk+ZNdL6cY/nNnz0mzZIwZrzll0kQrl4ChjNS3x5NdX30nOns5Cxb2vOP5PWJYdHuyWmptuXqEvLZPXdbiXbp91YbSDm8ovX+auulflOTNcEg3ZEuZnWsDUTirlW4="
